default: &default
  project_id: lilaboc-170106
  cloud_storage:
    bucket: lilaboc-170106
    access_key_id: GOOGBWJ7HUPQT62AGROO
    secret_access_key: 1Srzm1mZJTef5bf6vYtJ215Umq5EgMOtnIK7Pfr6
  oauth2:
    client_id: ayodeleamadi@gmail.com
    client_secret: ENV["gcloud_pass"]

development:
  <<: *default

production:
  <<: *default
